# Generated by Django 2.0 on 2018-10-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
    ]
