# Generated by Django 2.0 on 2018-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Avatar_image',
            field=models.CharField(default='url_image_name', max_length=50),
            preserve_default=False,
        ),
    ]
