Insert Into game_details Values(1,'checkers.jpg','checkers.swf','Arcade',3,'good game','3 in One Checkers');
Insert Into game_details Values(2,'360catcher.jpg','360catcher.swf','Arcade',2,'good game','360 Supreme Catcher');
Insert Into game_details Values(3,'3dsuperball.jpg','3dsuperball.jpg','Action',4,'good game','3D Super Ball');
Insert Into game_details Values(4,'41streality.jpg','41streality.swf','Action',4,'good game','41st Reality');
Insert Into game_details Values(5,'5differences.jpg','5differences.swf','Puzzle',4,'good game','5 Differences');
Insert Into game_details Values(6,'6differences.jpg','6differences.swf','Puzzle',4,'good game','6 Differences');
Insert Into game_details Values(7,'absea.jpg','absea.swf','Action',4,'good game','Abstract Sea');
Insert Into game_details Values(8,'adrenaline.jpg','adrenaline.swf','Sport',4,'good game','Adrenaline Challenge');
Insert Into game_details Values(9,'alaskanadversary.jpg','alaskanadversary.swf','Action',3,'Great graphics','Alaskan Adversary');
Insert Into game_details Values(10,'apokalyx.jpg','apokalyx.swf','Action',5,'Great graphics','Apokalyx');
Insert Into game_details Values(11,'applehunt.jpg','applehunt.swf','Arcade',4,'Great graphics','Apple Hunt');
Insert Into game_details Values(12,'arnesdemano.jpg','arnesdemano.swf','Action',4,'Great graphics','Arnes de Mano');
Insert Into game_details Values(13,'asteroidsrevenge3.jpg','asteroidsrevenge3.swf','Action',4,'Great graphics','Asteroids Revenge 3');
Insert Into game_details Values(14,'astroseries.jpg','astroseries.swf','Action',4,'Great graphics','Astroseries Millenia');
Insert Into game_details Values(15,'attackOTBGMT.jpg','attackOTBGMT.swf','Puzzle',3,'Great graphics','Attack OTBGMT');
Insert Into game_details Values(16,'autumnwar.jpg','autumnwar.swf','Strategy',2,'Great graphics','Autumn War');
Insert Into game_details Values(17,'ballpuzzle.jpg','ballpuzzle.swf','Puzzle',5,'Great graphics','Ball Puzzle');
Insert Into game_details Values(18,'battlestar.jpg','battlestar.swf','Strategy',4,'Great graphics','Battle Star Empire');
Insert Into game_details Values(19,'bigfish.jpg','bigfish.swf','Arcade',3,'Great graphics','Big Fish');
Insert Into game_details Values(20,'bitshift.jpg','bitshift.swf','Action',4,'Great graphics','Bitshift');
Insert Into game_details Values(21,'blueshift.jpg','blueshift.swf','Action',4,'Great graphics','Blueshift');
Insert Into game_details Values(22,'bountykillers.jpg','bountykillers.swf','Action',5,'Great graphics','Bounty Killers');
Insert Into game_details Values(23,'boxhead.jpg','boxhead.swf','Action',4,'Great graphics','Boxhead');
Insert Into game_details Values(24,'boxhead2play.jpg','boxhead2play.swf','Action',3,'Great graphics','Boxhead 2Play Rooms');
Insert Into game_details Values(25,'boxheadmorerooms.jpg','boxheadmorerooms.swf','Action',2,'Great graphics','Boxhead More Rooms');
Insert Into game_details Values(26,'boxhead_the_christmas_nightmare.jpg','boxhead_the_christmas_nightmare.swf','Action',4,'Great graphics','Boxhead the Christmas Nightmare');
Insert Into game_details Values(27,'boxhead_the_nightmare.jpg','boxhead_the_nightmare.swf','Action',5,'Great graphics','Boxhead the Nightmare');
Insert Into game_details Values(28,'boxhead_the_nightmare_biever_and_baby.jpg','boxhead_the_nightmare_biever_and_baby.swf','Action',3,'Awesome graphics','Boxhead the Nightmare:Biever and Baby');
Insert Into game_details Values(29,'boxheadrooms.jpg','boxheadrooms.swf','Action',4,'Great graphics','Boxhead The Rooms');
Insert Into game_details Values(30,'boxheadzw.jpg','boxheadzw.swf','Action',3,'Great graphics','Boxhead The Zombie Wars');
Insert Into game_details Values(31,'brainbots.jpg','brainbots.swf','Action',4,'Great graphics','Brainbots');
Insert Into game_details Values(32,'busyburger.jpg','busyburger.swf','Arcade',3,'Great graphics','Busy Burger');
Insert Into game_details Values(33,'braidy.jpg','braidy.swf','Arcade',3,'Great graphics','Captain Braidy');
Insert Into game_details Values(34,'captbraidy2.jpg','captbraidy2.swf','Arcade',4,'Great graphics','Captain Braidy2');
Insert Into game_details Values(35,'captbraidy3.jpg','captbraidy3.swf','Arcade',4,'Great graphics','Captain Braidy3');
Insert Into game_details Values(36,'caveescape.jpg','caveescape.swf','Arcade',3,'Great graphics','Cave Escape 2');
Insert Into game_details Values(37,'chargeball.jpg','chargeball.swf','Arcade',3,'Great graphics','Chargeball');
Insert Into game_details Values(38,'charmy.jpg','charmy.swf','Arcade',3,'Great graphics','Charmy the Orbz Collector');
Insert Into game_details Values(39,'chompy.jpg','chompy.swf','Arcade',4,'Great graphics','Chompy the Great');
Insert Into game_details Values(40,'chompywr.jpg','chompywr.swf','Arcade',4,'Great graphics','Chompys Winter Rescue');
Insert Into game_details Values(41,'climbingninja.jpg','climbingninja.swf','Arcade',3,'Great graphics','Climbing Ninja');
Insert Into game_details Values(42,'colorball2.jpg','colorball2.swf','Arcade',4,'Great graphics','Color Ball 2');
Insert Into game_details Values(43,'combots.jpg','combots.swf','Strategy',5,'Great graphics','comBOTS');
Insert Into game_details Values(44,'cometbuster.jpg','cometbuster.swf','Arcade',4,'Great graphics','Comet Buster');
Insert Into game_details Values(45,'cosmicblast.jpg','cosmicblast.swf','Action',4,'Great graphics','Cosmic Blast');
Insert Into game_details Values(46,'cosmiccrush.jpg','cosmiccrush.swf','Arcade',3,'Great graphics','Cosmic Crush');
Insert Into game_details Values(47,'crazyflasher2.jpg','crazyflasher2.swf','Action',4,'Great graphics','Crazy Flasher 2');
Insert Into game_details Values(48,'crazyflasher3.jpg','crazyflasher3.swf','Action',3,'Great graphics','Crazy Flasher 3');
Insert Into game_details Values(49,'crazyflasher4.jpg','crazyflasher4.swf','Action',4,'Great graphics','Crazy Flasher 4');
Insert Into game_details Values(50,'creeping.jpg','creeping.swf','Action',3,'Great graphics','Creeping');
Insert Into game_details Values(51,'cubetema.jpg','cubtema.swf','Puzzle',4,'Great graphics','Cube Tema');
Insert Into game_details Values(52,'darkhorizon.jpg','darkhorizon.swf','Arcade',5,'Great graphics','Dark Horizon');
Insert Into game_details Values(53,'darkbase.jpg','darkbase.swf','Action',4,'Great graphics','Darkbase');
Insert Into game_details Values(54,'darkbase3.jpg','darkbase3.swf','Action',4,'Great graphics','Darkbase 3');
Insert Into game_details Values(55,'Darkbase_Alien_RTS.jpg','Darkbase_Alien_RTS.swf','Strategy',5,'Great graphics','Darkbase Alien RTS');
Insert Into game_details Values(56,'darkbase_rts.jpg','darkbase_rts.swf','Strategy',4,'Great graphics','Darkbase RTS');
Insert Into game_details Values(57,'deadtree.jpg','deadtree.swf','Action',4,'Great graphics','Dead Tree Defender');
Insert Into game_details Values(58,'deathtrip.jpg','deathtrip.swf','Arcade',4,'Great graphics','Death Trip');
Insert Into game_details Values(59,'deathmatch.jpg','deathmatch.swf','Puzzle',3,'Great graphics','DeathMatch');
Insert Into game_details Values(60,'deepcreatures.jpg','deepcreatures.swf','Action',5,'Great graphics','Deep Creatures');
Insert Into game_details Values(61,'defendnorth.jpg','defendnorth.swf','Arcade',4,'Great graphics','');
Insert Into game_details Values(62,'detonate.jpg','detonate.swf','Arcade',4,'Great graphics','Detonate');
Insert Into game_details Values(63,'detonate2.jpg','detonate2.swf','Arcade',4,'Great graphics','Detonate 2');
Insert Into game_details Values(64,'dodohunt.jpg','dodohunt.swf','Action',3,'Great graphics','Dodo Hunt');
Insert Into game_details Values(65,'darkbase2.jpg','darkbase2.swf','Action',4,'Great graphics','Darkbase 2');
Insert Into game_details Values(66,'drowsfury.jpg','drowsfury.swf','Fantasy',4,'Great graphics','Drows Fury');
Insert Into game_details Values(67,'dryfire.jpg','dryfire.swf','Sport',3,'Great graphics','Dry_Fire');
Insert Into game_details Values(68,'dueladventure.jpg','dueladventure.swf','Strategy',4,'Great graphics','Duel Adventure');
Insert Into game_details Values(69,'duoblaster.jpg','duoblaster.swf','Arcade',3,'Great graphics','Duoblaster');
Insert Into game_details Values(70,'dupligon.jpg','dupligon.swf','Puzzle',2,'Great graphics','Dupligon');
Insert Into game_details Values(71,'eggyeaster.jpg','eggyeaster.swf','Action',3,'Great graphics','Eggy Easter');
Insert Into game_details Values(72,'endlesszombierampage.jpg','endlesszombierampage.swf','Action',3,'Great graphics','Endless Zombie Rampage');
Insert Into game_details Values(73,'endlesszombierampage2.jpg','endlesszombierampage2.swf','Action',4,'Great graphics','Endless Zombie Rampage 2');
Insert Into game_details Values(74,'eternalred.jpg','eternalred.swf','Action',3,'Great graphics','Eternal Red');
Insert Into game_details Values(75,'exofusion2.jpg','exofusion2.swf','Action',4,'Great graphics','Exofusion 2');
Insert Into game_details Values(76,'fith.jpg','fith.swf','Action',3,'Great graphics','Fire in the Hole');
Insert Into game_details Values(77,'fith2.jpg','fith2.swf','Action',4,'Great graphics','Fire in the Hole 2');
Insert Into game_details Values(78,'foofarace.jpg','foofarace.swf','Sport',4,'Great graphics','Foofa Race');
Insert Into game_details Values(79,'foofarace2.jpg','foofarace2.swf','Sport',4,'Great graphics','Foofa Race 2');
Insert Into game_details Values(80,'fooix.jpg','fooix.swf','Puzzle',3,'Great graphics','Fooix');
Insert Into game_details Values(81,'fracture.jpg','fracture.swf','Arcade',3,'Great graphics','Fracture');
Insert Into game_details Values(82,'fracture2.jpg','fracture2.swf','Arcade',4,'Great graphics','Fracture 2');
Insert Into game_details Values(83,'fragassault.jpg','fragassault.swf','Action',5,'Great graphics','Frag Assault');
Insert Into game_details Values(84,'frantic.jpg','frantic.swf','Action',4,'Great graphics','Frantic');
Insert Into game_details Values(85,'freewayfury.jpg','freewayfury.swf','Arcade',3,'Great graphics','Freeway Fury');
Insert Into game_details Values(86,'fuzzy.jpg','fuzzy.swf','Arcade',4,'Great graphics','Fuzzy McFluffenstein');
Insert Into game_details Values(87,'fuzzy2.jpg','fuzzy2.swf','Arcade',3,'Great graphics','Fuzzy McFluffenstein 2');
Insert Into game_details Values(88,'fuzzy3.jpg','fuzzy3.swf','Arcade',4,'Great graphics','Fuzzy McFluffenstein 3');
Insert Into game_details Values(89,'glaikittyfyke.jpg','glaikittyfyke.swf','Arcade',3,'Great graphics','Glaikitty Fyke');
Insert Into game_details Values(90,'gogoplant.jpg','gogoplant.swf','Action',4,'Great graphics','Go Go Plant');
Insert Into game_details Values(91,'gogoplant2.jpg','gogoplant2.swf','Action',5,'Great graphics','Go Go Plant 2');
Insert Into game_details Values(92,'goingup.jpg','goingup.swf','Arcade',3,'Great graphics','Going Up');
Insert Into game_details Values(93,'guy3.jpg','guy3.swf','Action',3,'Great graphics','Guy 3');
Insert Into game_details Values(94,'guy2.jpg','guy2.swf','Action',4,'Great graphics','Guys Revenge');
Insert Into game_details Values(95,'h-bounce.jpg','h-bounce.swf','Sport',4,'Great graphics','H bounce');
Insert Into game_details Values(96,'hangingaround.jpg','hangingaround.swf','Arcade',4,'Great graphics','Hanging Around');
Insert Into game_details Values(97,'hardcourt.jpg','hardcourt.swf','Sport',3,'Great graphics','Hardcourt');
Insert Into game_details Values(98,'helistorm2.jpg','helistorm2.swf','Action',4,'Great graphics','Helistorm 2');
Insert Into game_details Values(99,'hexstar.jpg','hexstar.swf','Arcade',4,'Great graphics','HexStar');
Insert Into game_details Values(100,'hotbloodboxing.jpg','hotbloodboxing.swf','Sport',5,'Great graphics','Hot Blood Boxing');
Insert Into game_details Values(101,'hotlz.jpg','hotlz.swf','Action',3,'Great graphics','Hot LZ');
Insert Into game_details Values(102,'hoverbotarena.jpg','hoverbotarena.swf','Action',4,'Great graphics','Hover Bot Arena');
Insert Into game_details Values(103,'hoverbotarena2.jpg','hoverbotarena2.swf','Action',3,'Great graphics','Hover Bot Arena 2');
Insert Into game_details Values(104,'hovertanks.jpg','hovertanks.swf','Action',4,'Great graphics','Hover Tanks');
Insert Into game_details Values(105,'hovertanks2.jpg','hovertanks2.swf','Action',5,'Great graphics','Hover Tanks');
Insert Into game_details Values(106,'hungryfish.jpg','hungryfish.swf','Arcade',3,'Great graphics','Hungry Fish');
Insert Into game_details Values(107,'inquisitivedave.jpg','inquisitivedave.swf','Adventure',3,'Great graphics','Inquisitive Dave');
Insert Into game_details Values(108,'jeeves.jpg','jeeves.swf','Sport',4,'Great graphics','Jeeves Volleyball');
Insert Into game_details Values(109,'jumpagon.jpg','jumpagon.swf','Arcade',3,'Great graphics','Jumpagon');
Insert Into game_details Values(110,'junospore.jpg','junospore.swf','Action',3,'Great graphics','Juno Spore');
Insert Into game_details Values(111,'killchristmas.jpg','killchristmas.swf','Action',3,'Great graphics','Kill Christmas');
Insert Into game_details Values(112,'kingdomkeeper.jpg','kingdomkeeper.swf','Fantasy',4,'Great graphics','Kingdom Keeper');
Insert Into game_details Values(113,'kingsisland.jpg','kingsisland.swf','Fantasy',4,'Great graphics','Kings Island');
Insert Into game_details Values(114,'kingsisland2.jpg','kingsisland2.swf','Fantasy',3,'Great graphics','Kings Island 2');
Insert Into game_details Values(115,'knox.jpg','knox.swf','Puzzle',3,'Great graphics','Knox');
Insert Into game_details Values(116,'krazykeys.jpg','krazykeys.swf','Arcade',4,'Great graphics','Krazy Keyz');
Insert Into game_details Values(117,'linerunner.jpg','linerunner.swf','Arcade',3,'Great graphics','Line Runner');
Insert Into game_details Values(118,'linearassault.jpg','linearassault.swf','Arcade',4,'Great graphics','Linear Assault');
Insert Into game_details Values(119,'linkaball.jpg','linkaball.swf','Arcade',4,'Great graphics','Linkaball');
Insert Into game_details Values(120,'loa.jpg','loa.swf','Action',4,'Great graphics','Loa and the Island Quest');
Insert Into game_details Values(121,'ladybug.jpg','ladybug.swf','Arcade',3,'Great graphics','Lucky Ladybug');
Insert Into game_details Values(122,'madmonday.jpg','madmonday.swf','Action',4,'Great graphics','Mad Monday');
Insert Into game_details Values(123,'madnesscombatdefense.jpg','madnesscombatdefense.swf','Action',4,'Great graphics','Madness Combat Defense');
Insert Into game_details Values(124,'manhunt.jpg','manhunt.swf','Action',3,'Great graphics','Manhunt');
Insert Into game_details Values(125,'mardek.jpg','mardek.swf','Fantasy',4,'Great graphics','Mardek');
Insert Into game_details Values(126,'mardek2.jpg','mardek2.swf','Fantasy',4,'Great graphics','Mardek 2');
Insert Into game_details Values(127,'massattack.jpg','massattack.swf','Arcade',3,'Great graphics','Mass Attack');
Insert Into game_details Values(128,'methustd.jpg','methustd.swf','Fantasy',5,'Great graphics','Methus Tower Defence');
Insert Into game_details Values(129,'mokomoko.jpg','mokomoko.swf','Arcade',4,'Great graphics','Moko Moko');
Insert Into game_details Values(130,'monstermaster.jpg','monstermaster.swf','Arcade',4,'Great graphics','Monster Master');
Insert Into game_details Values(131,'marathon.jpg','marathon.swf','Sport',4,'Great graphics','Moron Marathon');
Insert Into game_details Values(132,'motelconnection.jpg','motelconnection.swf','Action',3,'Great graphics','Motel Connection');
Insert Into game_details Values(133,'mrpenguin.jpg','mrpenguin.swf','Arcade',4,'Great graphics','Mr. Penguin');
Insert Into game_details Values(134,'msoids.jpg','msoids.swf','Action',3,'Great graphics','MSOIDS');
Insert Into game_details Values(135,'neon.jpg','neon.swf','Arcade',3,'Great graphics','Neon');
Insert Into game_details Values(136,'neon2.jpg','neon.swf','Arcade',4,'Great graphics','Neon 2');
Insert Into game_details Values(137,'neon2_5.jpg','neon2_5.swf','Action',4,'Great graphics','Neon 2.5');
Insert Into game_details Values(138,'nibbles.jpg','nibbles.swf','Arcade',4,'Great graphics','Nibbles');
Insert Into game_details Values(139,'nightmarekingdom.jpg','nightmarekingdom.swf','Action',5,'Great graphics','Nightmare Kingdom');
Insert Into game_details Values(140,'nomorereinforcements.jpg','nomorereinforcements.swf','Action',3,'Great graphics','No More Reinforcements');
Insert Into game_details Values(141,'nudge.jpg','nudge.swf','Arcade',4,'Great graphics','Nudge');
Insert Into game_details Values(142,'ogg.jpg','ogg.swf','Action',4,'Great graphics','Ogg the Squirrel Hunter');
Insert Into game_details Values(143,'omegawarrior.jpg','omegawarrior.swf','Action',4,'Great graphics','Omega Warrior');
Insert Into game_details Values(144,'orbital.jpg','orbital.swf','Arcade',5,'Great graphics','Orbital');
Insert Into game_details Values(145,'pandemic.jpg','pandemic.swf','Strategy',4,'Great graphics','Pandemic');
Insert Into game_details Values(146,'pandemic2.jpg','pandemic2.swf','Strategy',4,'Great graphics','Pandemic 2');
Insert Into game_details Values(147,'pandemicEOM.jpg','pandemicEOM.swf','Strategy',5,'Great graphics','Pandemic EoM');
Insert Into game_details Values(148,'pits.jpg','pits.swf','Arcade',4,'Great graphics','Panic in the Skyscraper ');
Insert Into game_details Values(149,'parajumper.jpg','parajumper.swf','Sport',4,'Great graphics','Para Jumper');
Insert Into game_details Values(150,'pigeon.jpg','pigeon.swf','Arcade',3,'Great graphics','Pigeons Revenge');
Insert Into game_details Values(151,'pigeon2.jpg','pigeon2.swf','Arcade',3,'Great graphics','Pigeons Revenge 2');
Insert Into game_details Values(152,'pirates.jpg','pirates.swf','Action',4,'Great graphics','Pirates');
Insert Into game_details Values(153,'pizzaboy.jpg','pizzaboy.swf','Arcade',4,'Great graphics','Pizzaboy');
Insert Into game_details Values(154,'planktonlife.jpg','planktonlife.swf','Arcade',5,'Great graphics','Plankton Life');
Insert Into game_details Values(155,'planktonlife2.jpg','planktonlife2.swf','Arcade',4,'Great graphics','Plankton Life 2');
Insert Into game_details Values(156,'playingfield.jpg','playingfield.swf','Arcade',4,'Great graphics','Playing Field 2');
Insert Into game_details Values(157,'playingfield2.jpg','playingfield2.swf','Arcade',4,'Great graphics','Playing Field 2');
Insert Into game_details Values(158,'poink.jpg','poink.swf','Arcade',2,'Great graphics','Poink');
Insert Into game_details Values(159,'postalpanic.jpg','postalpanic.swf','Action',3,'Great graphics','Postal Panic');
Insert Into game_details Values(160,'practicechapped.jpg','practicechapped.swf','Action',4,'Great graphics','Practice Chapped');
Insert Into game_details Values(161,'prisonthrow.jpg','prisonthrow.swf','Arcade',3,'Great graphics','Prison Throw');
Insert Into game_details Values(162,'pumpkinbattle.jpg','pumpkinbattle.swf','Fantasy',4,'Great graphics','Pumpkin Battle');
Insert Into game_details Values(163,'pumpkinrun.jpg','pumpkinrun.swf','Arcade',3,'Great graphics','Pumpkin Run');
Insert Into game_details Values(164,'pyroblossom.jpg','pyroblossom.swf','Action',3,'Great graphics','Pyroblossom');
Insert Into game_details Values(165,'quibeland.jpg','quibeland.swf','Action',4,'Great graphics','Quibeland');
Insert Into game_details Values(166,'quibelandevolution.jpg','quibelandevolution.swf','Action',5,'Great graphics','Quibeland Evolution');
Insert Into game_details Values(167,'qwerty.jpg','qwerty.swf','Action',4,'Great graphics','QWERTY Warriors');
Insert Into game_details Values(168,'qwerty2.jpg','qwerty2.swf','Action',4,'Great graphics','QWERTY Warriors 2');
Insert Into game_details Values(169,'rage.jpg','rage.swf','Action',2,'Great graphics','Rage');
Insert Into game_details Values(170,'raidenx.jpg','raidenx.swf','Action',2,'Great graphics','RaidenX');
Insert Into game_details Values(171,'rainwords.jpg','rainwords.swf','Puzzle',3,'Great graphics','Rain Words');
Insert Into game_details Values(172,'rainbowblitz.jpg','rainbowblitz.swf','Arcade',3,'Great graphics','Rainbow Blitz');
Insert Into game_details Values(173,'ratmaze2.jpg','ratmaze2.swf','Arcade',4,'Great graphics','Ratmaze 2');
Insert Into game_details Values(174,'reachthesky.jpg','reachthesky.swf','Arcade',4,'Great graphics','Reach the Sky');
Insert Into game_details Values(175,'rebounce.jpg','rebounce.swf','Arcade',3,'Great graphics','Rebounce');
Insert Into game_details Values(176,'redjetrabbit.jpg','redjetrabbit.swf','Action',4,'Great graphics','Red Jet Rabbit');
Insert Into game_details Values(177,'redwire.jpg','redwire.swf','Arcade',4,'Great graphics','Red Wire');
Insert Into game_details Values(178,'redshift.jpg','redshift.swf','Action',4,'Great graphics','Redshift');
Insert Into game_details Values(179,'rocketweasel.jpg','rocketweasel.swf','Arcade',3,'Great graphics','Rocket Weasel');
Insert Into game_details Values(180,'saturdaynightbloodfest.jpg','saturdaynightbloodfest.swf','Arcade',2,'Great graphics','Saturday Night Blood Fest');
Insert Into game_details Values(181,'saucerstrike.jpg','saucerstrike.swf','Arcade',3,'Great graphics','Saucer Strike');
Insert Into game_details Values(182,'savethearmy.jpg','savethearmy.swf','Arcade',4,'Great graphics','Save the Army');
Insert Into game_details Values(183,'saveusfromprivatebrian.jpg','saveusfromprivatebrian.swf','Action',4,'Great graphics','Save Us From Private Brian');
Insert Into game_details Values(184,'seascape.jpg','seascape.swf','Sport',3,'Great graphics','Seascape');
Insert Into game_details Values(185,'seasonofwar.jpg','seasonofwar.swf','Strategy',4,'Great graphics','Season of War');
Insert Into game_details Values(186,'shadez.jpg','shadez.swf','Action',5,'Great graphics','Shadez');
Insert Into game_details Values(187,'shadez2.jpg','shadez2.swf','Action',4,'Great graphics','Shadez 2');
Insert Into game_details Values(188,'shadez3.jpg','shadez3.swf','Action',4,'Great graphics','Shadez 3');
Insert Into game_details Values(189,'shotgunorc.jpg','shotgunorc.swf','Action',3,'Great graphics','Shotgun Orc');
Insert Into game_details Values(190,'skillstack.jpg','skillstack.swf','Arcade',4,'Great graphics','Skill Stack');
Insert Into game_details Values(191,'skychopper.jpg','skychopper.swf','Action',5,'Great graphics','Sky Chopper');
Insert Into game_details Values(192,'spellduelist.jpg','spellduelist.swf','Arcade',4,'Great graphics','Spell Duelist');
Insert Into game_details Values(193,'spiderbugs.jpg','spiderbugs.swf','Arcade',4,'Great graphics','Spider Bugs');
Insert Into game_details Values(194,'spitwad.jpg','spitwad.swf','Arcade',3,'Great graphics','Spitwad');
Insert Into game_details Values(195,'stabika2.jpg','stabika2.swf','Action',4,'Great graphics','Stabika 2');
Insert Into game_details Values(196,'stickdefense.jpg','stickdefense.swf','Action',5,'Great graphics','Stick Defense');
Insert Into game_details Values(197,'stickmansam1.jpg','stickmansam1.swf','Action',4,'Great graphics','Stickman Sam');
Insert Into game_details Values(198,'stickmansam2.jpg','stickmansam2.swf','Action',3,'Great graphics','Stickman Sam 2');
Insert Into game_details Values(199,'stickmansam3.jpg','stickmansam3.swf','Action',4,'Great graphics','Stickman Sam 3');
Insert Into game_details Values(200,'stickmansam4.jpg','stickmansam4.swf','Action',4,'Great graphics','Stickman Sam 4');
Insert Into game_details Values(201,'stinkybean.jpg','stinkybean.swf','Puzzle',3,'Great graphics','Stinky Bean');
Insert Into game_details Values(202,'stinkybean2.jpg','stinkybean2.swf','Puzzle',5,'Great graphics','Stinky Bean 2');
Insert Into game_details Values(203,'beanfling.jpg','beanfling.swf','Arcade',4,'Great graphics','Stinky Bean Fling');
Insert Into game_details Values(204,'strategydefense.jpg','strategydefense.swf','Strategy',4,'Great graphics','Strategy Defense');
Insert Into game_details Values(205,'strategydefense2.jpg','strategydefense2.swf','Strategy',4,'Great graphics','Strategy Defense 2');
Insert Into game_details Values(206,'strategydefense3.jpg','strategydefense3.swf','Strategy',4,'Great graphics','Strategy Defense 3');
Insert Into game_details Values(207,'strategydefense4.jpg','strategydefense4.swf','Strategy',4,'Great graphics','Strategy Defense 4');
Insert Into game_details Values(208,'strategydefense5.jpg','strategydefense5.swf','Strategy',4,'Great graphics','Strategy Defense 5');
Insert Into game_details Values(209,'superhyberdoze.jpg','superhyberdoze.swf','Arcade',4,'Great graphics','Super HyberDoze');
Insert Into game_details Values(210,'superninjastrike.jpg','superninjastrike.swf','Action',4,'Great graphics','Super Ninja Strike');
Insert Into game_details Values(211,'superpang.jpg','superpang.swf','Arcade',3,'Great graphics','Super Pang');
Insert Into game_details Values(212,'swarm2.jpg','swarm2.swf','Arcade',3,'Great graphics','Swarm 2');
Insert Into game_details Values(213,'tacass.jpg','tacass.swf','Action',4,'Great graphics','Tactical Assassin');
Insert Into game_details Values(214,'tacticalassassin2.jpg','tacticalassassin2.swf','Action',4,'Great graphics','Tactical Assassin 2');
Insert Into game_details Values(215,'tacass3.jpg','tacass3.swf','Action',4,'Great graphics','Tactical Assassin 3');
Insert Into game_details Values(216,'tacticalassassinsubstratum.jpg','tacticalassassinsubstratum.swf','Action',5,'Great graphics','Tactical Assassin Substratum');
Insert Into game_details Values(217,'tankpatrol.jpg','tankpatrol.swf','Action',4,'Great graphics','Tank Patrol');
Insert Into game_details Values(218,'telekineticeric.jpg','telekineticeric.swf','Action',3,'Great graphics','Telekinetic Eric');
Insert Into game_details Values(219,'legacyofguy.jpg','legacyofguy.swf','Arcade',4,'Great graphics','The Legacy of Guy');
Insert Into game_details Values(220,'ricehat.jpg','ricehat.swf','Action',4,'Great graphics','The Rice Hat Warrior');
Insert Into game_details Values(221,'thing_thing2.jpg','thing_thing2.swf','Action',3,'Great graphics','Thing Thing 2');
Insert Into game_details Values(222,'tt3.jpg','tt3.swf','Action',3,'Great graphics','Thing Thing 3');
Insert Into game_details Values(223,'thing_thing4.jpg','thing_thing4.swf','Action',3,'Great graphics','Thing Thing 4');
Insert Into game_details Values(224,'thing_thingarena.jpg','thing_thingarena.swf','Action',4,'Great graphics','Thing Thing Arena');
Insert Into game_details Values(225,'tta2.jpg','tta2.swf','Action',4,'Great graphics','Thing Thing Arena 2');
Insert Into game_details Values(226,'tta3.jpg','tta3.swf','Action',3,'Great graphics','Thing Thing Arena 3');
Insert Into game_details Values(227,'thing_thing_arena_classic.jpg','thing_thing_arena_classic.swf','Action',4,'Great graphics','Thing Thing Arena Classic');
Insert Into game_details Values(228,'thing_thing_arena_pro.jpg','thing_thing_arena_pro.swf','Action',5,'Great graphics','Thing Thing Arena Pro');
Insert Into game_details Values(229,'throughthemachine.jpg','throughthemachine.swf','Arcade',4,'Great graphics','Through the Machine');
Insert Into game_details Values(230,'tornado.jpg','tornado.swf','Arcade',3,'Great graphics','Tornado Button Smashing');
Insert Into game_details Values(231,'toxieradd.jpg','toxieradd.swf','Action',3,'Great graphics','Toxie Radd');
Insert Into game_details Values(232,'toxieradd2.jpg','toxieradd2.swf','Action',5,'Great graphics','Toxie Radd 2');
Insert Into game_details Values(233,'toxie_radd_3d.jpg','toxie_radd_3d.swf','Action',4,'Great graphics','Toxie Radd 3D');
Insert Into game_details Values(234,'treasureseas.jpg','treasureseas.swf','Action',4,'Great graphics','Treasure Seas Inc');
Insert Into game_details Values(235,'trid3nt.jpg','trid3nt.swf','Arcade',3,'Great graphics','Trid3nt');
Insert Into game_details Values(236,'trn47.jpg','trn47.swf','Arcade',5,'Great graphics','TRN 47 Subversion');
Insert Into game_details Values(237,'trollsrage.jpg','trollsrage.swf','Action',5,'Great graphics','Trolls Rage');
Insert Into game_details Values(238,'tcnx.jpg','tcnx.swf','Action',4,'Great graphics','Turbo Cyborg Ninja X');
Insert Into game_details Values(239,'turret.jpg','turret.swf','Action',4,'Great graphics','Turret Defense');
Insert Into game_details Values(240,'turretdefense2.jpg','turretdefense2.swf','Action',5,'Great graphics','Turret Defense 2');
Insert Into game_details Values(241,'type.jpg','type.swf','Arcade',4,'Great graphics','Tye Type Revolution');
Insert Into game_details Values(242,'ufglow.jpg','ufglow.swf','Arcade',3,'Great graphics','UFGlow');
Insert Into game_details Values(243,'ufomania.jpg','ufomania.swf','Arcade',4,'Great graphics','UFO Mania');
Insert Into game_details Values(244,'ultimatecrabbattle.jpg','ultimatecrabbattle.swf','Action',3,'Great graphics','Ultimate Crab Battle');
Insert Into game_details Values(245,'ultimatedefense.jpg','ultimatedefense.swf','Strategy',4,'Great graphics','Ultimate Defense');
Insert Into game_details Values(246,'unfairytales.jpg','unfairytales.swf','Fantasy',5,'Great graphics','Unfairy Tales');
Insert Into game_details Values(247,'vanjellies.jpg','vanjellies.swf','Arcade',3,'Great graphics','Van Jellies');
Insert Into game_details Values(248,'vanguards.jpg','vanguards.swf','Puzzle',4,'Great graphics','Vanguards');
Insert Into game_details Values(249,'visible.jpg','visible.swf','Action',3,'Great graphics','Visible');
Insert Into game_details Values(250,'visible2.jpg','visible2.swf','Action',5,'Great graphics','Visible 2');
Insert Into game_details Values(251,'warmachines.jpg','warmachines.swf','Strategy',4,'Great graphics','War Machines');
Insert Into game_details Values(252,'weaponsofmathsdestruction.jpg','weaponsofmathsdestruction.swf','Action',4,'Great graphics','Weapons of Maths Destruction');
Insert Into game_details Values(253,'wingsofglory.jpg','wingsofglory.swf','Action',2,'Great graphics','Wings of Glory');
Insert Into game_details Values(254,'wonderlight.jpg','wonderlight.swf','Arcade',3,'Great graphics','Wonderlight');
Insert Into game_details Values(255,'wone.jpg','wone.swf','Arcade',4,'Great graphics','wOne');
Insert Into game_details Values(256,'wone2.jpg','wone2.swf','Arcade',5,'Great graphics','wOne 2');
Insert Into game_details Values(257,'xrunning.jpg','xrunning.swf','Action',4,'Great graphics','xRunning');
Insert Into game_details Values(258,'zombiehorde.jpg','zombiehorde.swf','Action',3,'Great graphics','Zombie Horde');
Insert Into game_details Values(259,'zombiehorde2.jpg','zombiehorde2.swf','Action',5,'Great graphics','Zombie Horde 2');
Insert Into game_details Values(260,'zombiehorde3.jpg','zombiehorde3.swf','Action',4,'Great graphics','Zombie Horde 3');
Insert Into game_details Values(261,'zombiesurvival.jpg','zombiesurvival.swf','Action',4,'Great graphics','Zombie Survival');
