# Generated by Django 2.0 on 2018-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_images', models.CharField(max_length=30)),
                ('game_swf', models.CharField(max_length=30)),
                ('game_type', models.CharField(max_length=20)),
                ('game_rating', models.IntegerField(max_length=5)),
                ('game_comments', models.CharField(max_length=100)),
                ('game_display_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Game_Details',
            },
        ),
    ]
