# Generated by Django 2.0 on 2018-10-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Six_ages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('game_name', models.CharField(max_length=40)),
                ('uname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
