# Generated by Django 2.0 on 2018-10-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Six_ages', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_comments',
        ),
    ]
